// try catch example

/*
try{
    // expression
} catch { // optional catch handling since ES10
    // expression
}

try{
    // expression
} catch { // optional catch handling since ES10
    // expression
} finally {
    // expression is executed either it's error or not
}

try {
    // expression
} catch (err){
    // expression
    // method
    err.name;
    err.message;
    err.stack;
}

try {
    // expression
} catch (err){
    // expression
    // method
    err.name;
    err.message;
    err.stack;
} finally {
    // expression is executed either it's error or not
}

try {
    // expression
} catch (err){
    // expression
    // method
    err.name;
    err.message;
    err.stack;
    if (err instanceof ErrorType){
        // expression
        // method
        err.name;
        err.message;
        err.stack;
    } else {
        // expression
        // method
        err.name;
        err.message;
        err.stack;
    }
}

try {
    // expression
} catch (err){
    // expression
    // method
    err.name;
    err.message;
    err.stack;
    if (err instanceof ErrorType){
        // expression
        // method
        err.name;
        err.message;
        err.stack;
    } else {
        // expression
        // method
        err.name;
        err.message;
        err.stack;
    }
} finally {
    // expression is executed either it's error or not
}

// throw error
throw new ErrorType("message");

// create new error type
class NewErrorType extends Error {
    constructor(message) {
        super(message);
        this.name = "NewErrorType";
    }
}

*/
